apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: threads
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: threads
    spec:
      containers:
      - name: threads
        image: hemanth224/threads
        ports:
        - containerPort: 3000
   
